### ISSUE TITLE
Font for all text on form should be uniform

### ISSUE THREAD

**Issue by pedextt** [anandcsingh/3for3#13]

**Comment by anandcsingh** [comment]
The text you see for name email etc is placeholder text that is rendered by the browser. It changes when you enter information. I cannot seem to change that placeholder with css even though it is said that I can

**Comment by pedextt** [comment]
I actually like the style of the text in the name and email fields. If the gender, country, pledge fields could match that style, that would be great.

**Comment by anandcsingh** [comment]
Sigh, tried that too but it can't be exact (the size). Also the light gray usually associated with watermarks/placeholder. But if you want it so it shall be done

-----Original Message-----

**Comment by anandcsingh** [comment]
This is done would you agree?
