### ISSUE TITLE
Create section below pledge form

### ISSUE THREAD

**Issue by pedextt** [anandcsingh/3for3#22]
Partners

Do you or your company supply any of the products or services we have recommended to reduce individual consumption (e.g. stainless steel reusable water bottles, gift fabric, paperless billing, etc.)? Let's discuss opportunities for partnership to extend the reach of your products and services. Contact us!

**Comment by anandcsingh** [comment]
you need to draw or mockup something as I cannot imagine this in my mind's eye

**Comment by pedextt** [comment]
How about just in your mind?

Right now we have three sections with alternating background colours.

Pledge 3 for 3 WED 2015
Description
----
Pledges
Pledge check list
----
Pledge form


I am suggesting a fourth under the pledge form (white background). It will be similar to the first in that right now it will just be a description

Heading: Partners
Description: Do you or your company supply any of the products or services we have recommended to reduce individual consumption (e.g. stainless steel reusable water bottles, gift fabric, paperless billing, etc.)? Let's discuss opportunities for partnership to extend the reach of your products and services. Contact us!

The idea is that if companies come on board, their logos will be placed here.
