### ISSUE TITLE
Share pledge on social media

### ISSUE THREAD

**Issue by anandcsingh** [anandcsingh/3for3#5]
Add the ability to share the pledge on Facebook etc. Include a link to the website to encourage friends to join.

**Comment by anandcsingh** [comment]
Needs to be tested do we have test social media accounts to test on?

**Comment by pedextt** [comment]
No test account. 

Sincerely,
Sharda Beharry 
Director
Project for Educational Excellence  

-----Original Message-----

**Comment by anandcsingh** [comment]
Tested them out this morning, they work fine.
