### ISSUE TITLE
Pledge buttons are not aligned

### ISSUE THREAD

**Issue by pedextt** [anandcsingh/3for3#8]
The last button does not align with the first two. It is shifted to the left.

**Comment by anandcsingh** [comment]
What are you going after here? The buttons are not aligned but the form button is closer to the end of the form.
Also they are different sizes, do you want them to be the same size?
Also from what device where you looking at it?

**Comment by pedextt** [comment]
Ok, it just seemed odd when I was scrolling. Good point about the position being near to the end of the form. It's fine, leave the position as is. Same size would be good
